SELECT DISTINCT 
RCTLGDA.CUSTOMER_TRX_ID AS CUSTOMER_TRX_ID, 
PEIA.EXPENDITURE_ITEM_ID AS PA_TRANS_ID

FROM 
TABLE_1 RCTLGDA,
TABLE_2 PEIA

WHERE
RCTLGDA.TRANSACTION_TYPE = 'CAPITAL'
AND RCTLGDA.EXPENDITURE_ITEM_ID = PEIA.EXPENDITURE_ITEM_ID
