SELECT DISTINCT 
RCTLGDA.CUSTOMER_TRX_ID AS CUSTOMER_TRX_ID, 
PEIA.EXPENDITURE_ITEM_ID AS PA_TRANS_ID

FROM 
TABLE_1 RCTLGDA
INNER JOIN TABLE_2 PEIA
ON RCTLGDA.EXPENDITURE_ITEM_ID = PEIA.EXPENDITURE_ITEM_ID

WHERE
RCTLGDA.TRANSACTION_TYPE = 'CAPITAL'