SELECT DISTINCT

RCTLGDA.CUSTOMER_TRX_ID AS CUSTOMER_TRX_ID,

PEIA.EXPENDITURE_ITEM_ID AS PA_TRANS_ID,
PEIA.EXPENDITURE_ITEM_DATE AS ITEM_DATE,
PEIA.CC_PRVDR_ORGANIZATION_ID AS PROVIDER_OU,
PEIA.CC_RECVR_ORGANIZATION_ID AS RECEIVER_OU,
PEIA.EXPENDITURE_TYPE AS EXPENDITURE_TYPE,
PEIA.QUANTITY AS QUANTITY,
PEIA.UNIT_OF_MEASURE AS UOM,
PEIA.PROJECT_RAW_COST AS RAW_COST_RATE,
PEIA.DENOM_BURDENED_COST AS COST,
PEIA.DENOM_CURRENCY_CODE AS ENTERED_CURRENCY,
PEIA.DENOM_RAW_COST AS COST_IN_USD

FROM 
APPS.PA_EXPENDITURE_ITEMS_ALL PEIA,
APPS.PA_PROJECTS_ALL PPA,
APPS.PA_TASKS PT,
APPS.PA_TRANSACTION_SOURCES PTS,
APPS.PA_EXPENDITURE_COMMENTS PEC,
APPS.AP_SUPPLIERS APS,
APPS.PA_DRAFT_INVOICE_DETAILS_ALL PDIDA,
APPS.PA_DRAFT_INVOICES_ALL PDIA,
APPS.PA_DRAFT_INVOICE_ITEMS PDI,
APPS.RA_CUSTOMER_TRX_LINES_ALL RCTLA,
APPS.RA_CUSTOMER_TRX_ALL RCTA,
APPS.RA_CUST_TRX_LINE_GL_DIST_ALL RCTLGDA

WHERE 
PEIA.PROJECT_ID = PPA.PROJECT_ID
AND PEIA.TASK_ID = PT.TASK_ID
AND PEIA.TRANSACTION_SOURCE = PTS.TRANSACTION_SOURCE(+)
AND PEIA.EXPENDITURE_ITEM_ID = PEC.EXPENDITURE_ITEM_ID(+)
AND PEIA.VENDOR_ID = APS.VENDOR_ID(+)
AND PEIA.EXPENDITURE_ITEM_ID = PDIDA.EXPENDITURE_ITEM_ID(+)